import {React, useEffect,useRef,useState} from "react";
import { AiOutlineUser } from "react-icons/ai";
import { ProSidebar, Menu, MenuItem, SubMenu } from "react-pro-sidebar";



import SideBar from "../components/SideBar"

const styles = {
    display: 'flex',
    justifyContent: 'space-between'
}

 export default function UserProfil(){
    return (
        
        
        <div className="user-profil" style={styles}>
                <SideBar />
            <div className="user-profil-content">

"Neque porro quisquam est qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit...
"There is no one who loves pain itself, who seeks after it and wants to have it, simply because it is pain..."
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec luctus nunc vel hendrerit volutpat. Nullam sed blandit magna. Nam ut felis aliquam, euismod risus et, auctor justo. Vestibulum ac libero erat. Etiam vel rutrum nibh. Aliquam erat volutpat. Duis convallis ligula ut hendrerit molestie. Integer sollicitudin interdum orci, sit amet facilisis est luctus a. Nam quis malesuada massa. In interdum placerat ipsum non interdum. Nunc semper ex magna, eget lobortis ante cursus sed. Quisque et leo porta, interdum risus non, facilisis leo. Sed laoreet finibus nunc, quis dictum nisi condimentum sed. Praesent bibendum ultrices nibh eget congue.
Donec fermentum dui eros, in egestas libero consectetur id. Donec id purus id lacus tempor tincidunt. Pellentesque tempus quis nulla at posuere. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Pellentesque ac risus consectetur, tempor urna vitae, iaculis ipsum. Duis mattis ultricies erat. Suspendisse aliquet convallis nisi. Phasellus aliquam enim quis sollicitudin imperdiet. Nulla consequat lacus a velit placerat porta. Nam ante enim, ullamcorper quis fringilla in, iaculis eget tortor. Ut mollis lectus sem, ut ultricies elit faucibus in. Duis non dui velit. Mauris scelerisque nibh eget tempor tincidunt. Ut ac pulvinar ipsum.
Quisque non placerat lectus. Aliquam tristique tristique vehicula. Maecenas quis turpis in risus placerat luctus in in lectus. Cras malesuada magna enim, a consectetur leo venenatis non. Integer eu cursus risus. Phasellus eget tincidunt tortor, et sagittis neque. Fusce molestie interdum quam, nec accumsan diam ultricies ac.
Proin sollicitudin bibendum tempus. Quisque a ultricies libero, at condimentum nulla. Aliquam a ligula non est sollicitudin posuere ac id magna. Etiam vestibulum elit quis maximus bibendum. Vivamus consectetur dapibus laoreet. Duis consectetur elit vitae elit porta, sit amet venenatis sapien dignissim. Curabitur tincidunt venenatis nisl, et faucibus erat ornare id. Morbi ac tellus et nisl vestibulum finibus. Mauris sem magna, pellentesque id sodales eget, facilisis quis velit. Ut porta libero rhoncus felis cursus tincidunt. Phasellus eu condimentum libero.
Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Aenean pulvinar dui vitae metus commodo, sed vehicula erat molestie. Vivamus nunc nisi, dictum vel nibh eget, auctor interdum arcu. Mauris at imperdiet diam. Cras nisl dolor, consectetur ac purus id, pharetra sollicitudin justo. Quisque accumsan neque molestie ultrices scelerisque. Maecenas lacinia malesuada suscipit. Fusce cursus semper massa, eu pretium odio luctus ac. Integer finibus libero quis volutpat tincidunt. Etiam vitae dolor sed ligula iaculis varius.
Vivamus nibh arcu, varius laoreet ligula nec, vulputate hendrerit diam. Duis luctus eu ante a imperdiet. Nulla sed volutpat dui. Suspendisse potenti. Aenean consectetur metus non tristique tincidunt. Donec quis pharetra dolor, pharetra laoreet metus. Etiam nec magna sit amet nisl placerat sollicitudin. Vivamus pellentesque, urna in fringilla mattis, libero felis euismod metus, sit amet lacinia elit eros eget arcu. Donec pellentesque tortor odio, eu porttitor elit laoreet id. Fusce elementum mauris ac nibh varius fermentum. Morbi placerat vehicula velit non commodo.
Proin ultricies condimentum diam eu iaculis. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Cras nec blandit mi. Nullam porta sed ex vel fermentum. Quisque vulputate porttitor tincidunt. Donec porta ex lacinia, porttitor mauris a, efficitur orci.
Donec eget sem est. Aenean dapibus pulvinar mollis. Vivamus in arcu finibus, tincidunt arcu quis, lacinia massa. Cras nec ipsum sit amet tellus sodales accumsan vitae et metus. Cras tincidunt lacinia arcu, in fringilla nulla blandit non. Donec quis libero eget justo eleifend vestibulum luctus at tortor. Nam a blandit mauris. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Sed rutrum dictum venenatis. Pellentesque elementum bibendum ex, id fermentum est tristique in. Ut aliquam hendrerit nulla quis tristique. Nunc vitae risus vitae nulla congue congue eget tincidunt nisi. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse venenatis massa tellus, accumsan rutrum nulla porta eu.
Vivamus sem lorem, aliquam et commodo sit amet, tempus id neque. Duis at gravida nisl. Duis viverra ultricies odio, eu viverra nulla. Etiam tincidunt nisi in magna congue cursus. Curabitur condimentum augue pharetra enim aliquet mollis sed non felis. Suspendisse ornare, massa ut ornare efficitur, velit arcu vehicula elit, nec lacinia magna mauris nec justo. Phasellus sed varius metus. Nam nec augue ac lacus vulputate sodales ac non nibh. Quisque erat lacus, pharetra vitae purus at, blandit tristique ex. Nulla id neque nec mauris tempor tincidunt.
In fermentum orci urna, quis pulvinar enim dictum vitae. Aliquam a enim vitae libero rhoncus malesuada. Vestibulum eu blandit mauris, at aliquam lorem. Nunc massa ipsum, convallis vel semper id, pulvinar dictum elit. Nam fringilla lectus vitae mattis fringilla. Sed blandit aliquet leo, vel sollicitudin justo faucibus id. Donec pulvinar malesuada sem, vitae luctus lorem vulputate ut. Cras ipsum ante, ultrices at tempus laoreet, pulvinar ac nisi. Donec dolor felis, rhoncus tempor tempor eu, facilisis vitae sem. Donec sit amet maximus sapien, nec iaculis risus.
Phasellus eu mauris sit amet dolor pretium porttitor nec sit amet mauris. Curabitur dapibus lacus vel velit suscipit accumsan. Nam faucibus et nisl vel mattis. Nunc fringilla efficitur nunc, in hendrerit ex. Praesent porttitor mauris elit, sit amet convallis justo cursus at. Cras congue malesuada massa, a lobortis diam facilisis nec. Integer nunc neque, iaculis vel enim a, vulputate pretium ipsum. Mauris suscipit maximus volutpat. In pulvinar nisi ut ante euismod, ac venenatis leo lacinia.
Vivamus a tortor elit. Curabitur eget viverra neque. Sed gravida non ex eu maximus. Praesent blandit, dolor ut facilisis dictum, mi arcu egestas magna, id euismod est sapien aliquam libero. Cras aliquam sit amet ipsum et pulvinar. Fusce commodo tempus aliquam. Donec ut fringilla leo. Donec libero diam, venenatis non diam quis, tempus tincidunt turpis. Vestibulum iaculis blandit vulputate.
Nam et gravida ligula, id ultrices tellus. Duis posuere risus eu diam convallis, et accumsan ligula faucibus. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Fusce eget enim erat. Nulla vitae congue nisi. Nam semper dui id pulvinar congue. Sed metus nunc, tempus gravida dignissim nec, ultricies aliquet lorem.
Vivamus fringilla sapien arcu, vitae pulvinar urna pellentesque quis. Morbi pulvinar ullamcorper vulputate. Nulla vel nisl sit amet ipsum volutpat imperdiet et in quam. Vestibulum non magna orci. Nullam scelerisque vehicula finibus. Vestibulum id maximus elit, quis sollicitudin elit. Sed euismod sollicitudin mi. Pellentesque metus nulla, placerat porta finibus ut, semper quis ipsum. Donec posuere odio nulla, ut eleifend lorem dapibus id. Morbi dignissim a nisi a tincidunt. Vivamus finibus magna quis placerat tincidunt. In cursus ultricies enim, vel ornare augue vestibulum nec. In lacus justo, vestibulum at lacus vitae, volutpat porttitor dui. Nam facilisis cursus diam non viverra.
Nulla quis augue nibh. Cras bibendum finibus imperdiet. Proin ornare accumsan urna, faucibus sagittis nisi semper ut. Morbi pretium odio eget dolor hendrerit, a volutpat leo elementum. Aliquam eget dui convallis tortor bibendum egestas. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Vivamus pharetra auctor facilisis. Sed dui justo, condimentum ut orci vitae, vestibulum tempus nisl. Cras venenatis dignissim arcu. Donec ultrices, neque non finibus luctus, mi erat suscipit purus, sit amet varius quam arcu sit amet ipsum. Nulla odio mauris, bibendum non viverra eget, euismod vitae arcu
Etiam ultricies pharetra mi nec accumsan. Vivamus interdum sem et tellus sollicitudin, eu gravida libero hendrerit. Etiam ut felis condimentum purus pellentesque efficitur vitae in orci. Quisque tempor metus eu leo rutrum ullamcorper. Etiam nec vulputate massa. Curabitur id mi vitae diam ornare interdum. Cras porttitor augue vel eleifend sollicitudin. Cras ut interdum eros. Cras eu ante dolor.
Aliquam eu metus in nulla consequat facilisis. Integer congue viverra iaculis. Quisque iaculis tortor vel urna pharetra rhoncus. Phasellus a arcu ut enim commodo tincidunt. Mauris eget dui volutpat, ullamcorper nulla ac, lobortis nibh. Interdum et malesuada fames ac ante ipsum primis in faucibus. Nam auctor lobortis lacus, ut viverra nisi mattis eu. Aliquam aliquam nisl sapien, ac tempus nulla sollicitudin sed. Curabitur felis elit, rutrum et metus et, convallis bibendum enim. Maecenas finibus mauris at tellus semper, eu elementum est ultrices.
Nunc ultricies hendrerit diam, quis blandit velit maximus vel. Donec at fringilla diam, ornare finibus libero. Vestibulum at egestas sem. Aliquam facilisis ornare felis, nec aliquam mauris pulvinar vitae. Phasellus iaculis nisl sed lectus dapibus efficitur. Quisque euismod turpis nec suscipit ullamcorper. Proin porta posuere felis a condimentum. Fusce aliquam et ex non pharetra. Morbi placerat nunc et sodales faucibus. Quisque vehicula arcu et accumsan gravida.
Vivamus laoreet molestie massa sed scelerisque. Etiam nec metus est. Vestibulum nisi enim, rhoncus in auctor a, tempus ut erat. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Suspendisse convallis rutrum justo ut venenatis. Donec pharetra tellus quam. Nunc vulputate hendrerit vehicula. Sed dolor massa, bibendum in condimentum in, rutrum sed lorem.
Ut et tortor finibus, placerat nulla ut, mollis tortor. Phasellus egestas odio leo, a sodales diam aliquam feugiat. Praesent tincidunt euismod mauris porta aliquet. Aliquam erat volutpat. Phasellus augue ex, congue vel ligula sit amet, congue pulvinar sem. Praesent id consectetur dui. Maecenas nec iaculis metus, ac tristique orci. Ut at massa mi. Pellentesque auctor rhoncus fringilla. Nullam cursus ac nisl at posuere. Sed at felis dapibus, laoreet quam eu, imperdiet magna. Duis ac euismod neque. Nunc facilisis ex sit amet enim sagittis feugiat. Donec ac est diam. Donec eu auctor velit. Quisque ornare velit et turpis pretium, ac volutpat lectus eleifend.
Donec molestie turpis nec hendrerit pharetra. Morbi feugiat ipsum id tellus dictum fringilla. Donec ac nisi vitae purus varius imperdiet. Fusce tincidunt nisi id magna hendrerit dapibus. Nam leo sem, pharetra a ornare eu, accumsan eget risus. Nullam ultricies accumsan quam ac maximus. Morbi ante risus, posuere non consequat non, aliquet vitae lectus. Duis vitae porttitor erat. Morbi purus dolor, condimentum vitae volutpat quis, lacinia vel augue. In pretium mi vitae dictum scelerisque. Fusce in justo eu risus consectetur congue a non metus.
Morbi accumsan, nibh sit amet aliquam maximus, eros justo maximus arcu, sit amet rhoncus felis tortor eu odio. Suspendisse vulputate, sapien nec sollicitudin mollis, urna risus aliquet purus, nec cursus massa turpis nec mi. Cras scelerisque nunc nec enim ultrices lobortis. Nunc at nulla ac ipsum accumsan efficitur at ac quam. Nullam risus arcu, imperdiet eu elit ac, egestas tincidunt dui. Cras tristique, mauris eu ultricies pharetra, nunc urna finibus lorem, non commodo odio est sit amet diam. Sed et aliquam risus. Etiam pharetra condimentum tincidunt. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae;
Nulla ac ante elementum lacus tempor maximus at sit amet augue. Donec felis mauris, posuere iaculis viverra ut, viverra rhoncus arcu. Fusce blandit at nulla vel vestibulum. Suspendisse scelerisque ex neque, ac cursus erat ultrices ut. Mauris et justo scelerisque, mollis eros eu, iaculis nibh. Vestibulum consequat ligula urna, id posuere metus facilisis at. Mauris porttitor, sem vitae ornare placerat, sem tortor semper quam, mattis condimentum erat eros ut quam.
Nunc at nulla dignissim eros suscipit placerat quis a augue. Nulla egestas sem tortor, id lacinia turpis sollicitudin eget. Sed ante nisi, maximus eu libero eget, iaculis auctor nisl. Curabitur vehicula id neque id auctor. Sed venenatis sollicitudin leo non egestas. Aenean a scelerisque mi. Ut sodales nunc a lorem laoreet egestas. Etiam elementum mauris purus, sit amet facilisis nisl commodo eget. Duis molestie ac lacus eu convallis. Aliquam sed sem eget quam rutrum rhoncus.
Fusce tincidunt libero nec risus vehicula porta. In iaculis tempor sollicitudin. Pellentesque non maximus purus, eget ultrices tortor. Vivamus erat augue, sagittis vitae justo quis, viverra fermentum libero. Proin justo nibh, vehicula sit amet ultrices sed, pretium non velit. Mauris egestas massa nec molestie ultricies. Aenean non elit blandit, pretium dui sit amet, ornare tellus. Nam scelerisque risus massa, et placerat dui faucibus sit amet. Suspendisse justo velit, maximus vitae arcu non, porttitor consequat lacus. Morbi at suscipit leo. Nunc cursus elit in volutpat commodo. Fusce elementum hendrerit pellentesque. Curabitur in quam dignissim, facilisis lacus at, ultricies massa. Duis nisi est, pharetra sit amet nunc in, laoreet tempor sem. Ut nec maximus mauris. Ut at mauris nec elit vestibulum vestibulum at vitae leo.
Vivamus vitae elit non ante mattis laoreet. Sed ullamcorper tempor felis, eget maximus justo efficitur ullamcorper. Quisque tincidunt facilisis diam, at semper turpis rutrum et. Aliquam porta maximus leo, eget euismod magna pulvinar eget. Curabitur tempus condimentum eros, ut vestibulum elit posuere eget. Nulla sit amet ullamcorper dui, vitae suscipit libero. Pellentesque bibendum arcu aliquet vulputate dapibus. Aliquam non viverra eros. Etiam sit amet magna ac tellus fermentum tincidunt. Mauris fringilla leo in nulla ornare tempus. Vestibulum vitae fringilla neque, ac rutrum enim. Aenean massa lorem, iaculis in lectus eget, facilisis pulvinar quam.
Aliquam elit ipsum, consequat ac odio eu, vestibulum laoreet nulla. Nunc vel diam facilisis quam rhoncus mattis sed eget erat. Etiam luctus in ante sed commodo. Nullam gravida tristique diam a sagittis. Vestibulum posuere rutrum metus eu luctus. Sed facilisis magna lorem, eget molestie sem efficitur ac. Vivamus vitae ligula luctus dolor pretium tincidunt. Aenean ultrices ac tortor id gravida. Donec congue, mauris sed laoreet aliquet, ipsum libero dapibus arcu, in dapibus dui leo faucibus est. Vestibulum consequat neque nisi, aliquet pretium orci sagittis eget. Proin et risus elit. Cras orci erat, porta porta sagittis pulvinar, molestie non lorem. Vivamus sem dolor, suscipit sed cursus quis, faucibus id arcu.
Nam ipsum ex, placerat mattis ante at, sagittis pharetra magna. Aenean a ante consectetur, fringilla nibh molestie, scelerisque ligula. In et magna vitae mauris lacinia commodo ultrices in velit. Nam gravida, felis id consectetur volutpat, leo metus iaculis turpis, vel facilisis neque dui sed dolor. Nullam sollicitudin nulla sit amet tempus condimentum. Vestibulum pulvinar massa eu ipsum efficitur convallis. Vestibulum vel nisl arcu. Aliquam diam nunc, faucibus maximus metus eu, interdum feugiat tellus. Praesent id nibh vitae eros varius elementum. Etiam sagittis gravida lorem quis dapibus. Aenean erat massa, semper eu volutpat ut, convallis sit amet sem.
Mauris placerat aliquet lacus, sed semper metus hendrerit sed. Fusce id bibendum ante, nec ultrices dolor. Proin non semper orci. Etiam sed vestibulum ante, nec ullamcorper est. Donec in justo sed orci gravida malesuada. Sed nunc magna, mattis eu sem eget, semper tincidunt risus. Vestibulum sagittis in enim a eleifend. Nam sed enim varius, bibendum mi lobortis, sollicitudin eros.
Aliquam venenatis cursus augue vel sagittis. Donec velit ante, viverra a dictum ac, consectetur in tortor. Cras sit amet hendrerit velit, ac ultrices arcu. Quisque euismod turpis ornare suscipit elementum. Nullam ornare condimentum odio, at bibendum erat luctus a. Vestibulum pharetra nibh vitae nibh ornare malesuada. Curabitur vitae sapien dui. Mauris ornare quam vel felis dictum fringilla. Morbi commodo dui in metus sodales, quis suscipit sem rhoncus. Donec convallis, nunc a sagittis accumsan, sapien libero tempus justo, vitae suscipit lacus diam a massa. Ut rutrum, dui vel dignissim pulvinar, lacus nulla auctor ante, quis convallis libero felis ut justo. Duis tincidunt, est eu pellentesque cursus, odio odio aliquam ante, id finibus elit ex quis ante.
Generated 30 paragraphs, 2498 words, 16841 bytes of Lorem Ipsum
help@lipsum.com
Privacy Policy

            </div>
        </div>
    )
}



export default UserProfil
