stages:
  - build
  - test

build-stage:
  stage: build
  script:
    - echo "Building..."
    - mkdir build
    - touch build/proof.txt

test-stage:
  stage: test
  script:
    - echo "Testing..."
    - test -f build/proof.txt
