# Frond_End
name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 16
        cache: 'npm'
    - name: setupfront
      working-directory: ./back-end
      run: ls 
    - name: installation des dependances
      working-directory: ./bakc-end
      run: npm ci
    - name: build du code
      working-directory: ./back-end
      run: npm run build --if-present
    - name: test du code
      working-directory: ./back-end
      run: npm test
