# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 16
        cache: 'npm'
    - name: setupfront
      working-directory: ./front-end
      run: ls 
    - name: installation des dependances
      working-directory: ./front-end
      run: npm ci
    - name: build du code
      working-directory: ./front-end
      run: npm run build --if-present
    - name: test du code
      working-directory: ./front-end
      run: npm test
